import { CustomFieldModel } from "./customfield";

export interface FacilityModel {
    ID: number;
    APPROVAL_STATUS: string;
    UPD_SEQ: number;
    AMND_STATE: string;
    FACILITY_CODE: string;
    PARENT_ID: number;
    DEPT_ID: number;
    CUSTOMER_ID: number;
    CURRENCY_ID: number;
    FACILITY_LIMIT: number;
    EXISTING_LIMIT: number;
    CREDIT_CONTRACT_DATE: Date;
    CREDIT_CONTRACT_NUMBER: string;
    DEBT_ACK_TENOR: number;
    DISBURSEMENT_PERIOD: number;
    FACILITY_DESC: string;
    LIMIT_SCHEMA: string;
    PRODUCT_ID: number;
    RATE_REVIEW_TERM: number;
    SUBMIT_TENOR: number;
    SUBMIT_RATE: number;
    REVOLVING: number;
    OUTSTANDING_PRICIPLE: number;
    OUTSTANDING_INTEREST: number;
    TOTAL_DISBURSEMENT_AMOUNT: number;
    MAX_DISBURSEMENT: number;
    EFFECTIVE_DATE: Date;
    DISBURSEMENT_END_DATE: Date;
    END_DATE: Date;
    STATUS: string;
    SID: number;
    TOTAL_DISBURSEMENT: number;
    FACILITY_TYPE: number;
    SECURE_LIMIT: number;
    UNSECURE_LIMIT: number;
    SYS_TRAN_ID: number;
    AUDIT_DATE: Date;
    AUDIT_OPERATION: string;
    RELATIONSHIP_MANAGER_ID: number;
    EXT_REF_NO_1: string;
    EXT_REF_NO_2: string;
    AUDIT_FIELDS: string;
    IS_MASTER: number;
    FIRST_DISBURSEMENT: number;
    EXT_REF_NO_3: string;
    EXT_REF_NO_4: string;
    EXT_REF_NO_5: string;
    RELATED_FAC_ID: number;
    LAST_CONTRACT_DATE: Date;
    SUBMIT_TENOR_UNIT: string;
    DISBURSEMENT_PERIOD_UNIT: string;
    FIRST_DISBURSEMENT_UNIT: string;
    DEBT_ACK_TENOR_UNIT: string;
    MAX_DISBURSEMENT_AMT: number;
    ListCustomField: CustomFieldModel[];
}
export interface FacilityTypeModel {
    ID: number;
    FACILITY_TYPE: string;
    DESCRIPTION: string;
}